apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: school-dashboard-ingress
  namespace: school-dashboard
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec: 
  ingressClassName: nginx
  rules:
    - host: school-dashboard.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: school-frontend-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: school-backend-service
                port:
                  number: 5000