apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: school-dashboard
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'school-backend'
        metrics_path: /metrics
        static_configs:
          - targets: ['school-backend-service:5000']